### PR TITLE
fix js array methods on README.md

### PR DESCRIPTION
**Pull request by danveb**
New contributor here. Was reading README and would like to fix js array methods I found.

### CODE REVIEW

**Comment by danveb** [comment]
accidentally closed pull request. Requesting to be reopened.

**Review by tejas-2232 — APPROVED** [review]
**Perfectly Done.**
**Every step is present as expected.**

**Comment by tejas-2232** [comment]
Thanks @danveb  for contributing.

__Hope you are enjoying Hacktoberfest__ :octocat:

**Comment by danveb** [comment]
Thanks @tejas-2232 for approval. Happy Hacktoberfest!

**Pull request merged**
