### PR TITLE
Added a Algorithm named Valid parentheses

### PR DESCRIPTION
**Pull request by komalreddy3**
As for the rules, created a new folder of algorithm Valid Parantheses which contains the js file and updated the same in readme file

### CODE REVIEW

**Comment by tejas-2232** [comment]
Hi Komal, Thanks for contributing. Your PR is under review. Have a good day!

**Comment by tejas-2232** [comment]
> As for the rules, created a new folder of algorithm Valid Parantheses which contains the js file and updated the same in readme file

Well the PR looks good, except - the spelling of parentheses in README file is not correct and please rename the folder from **validParantheses_15** to **15. Valid Parentheses**

**Comment by komalreddy3** [comment]
I have done the Modifications as requested , Please let me know if there is anything else to be done

**Comment by tejas-2232** [comment]
> I have done the Modifications as requested , Please let me know if there is anything else to be done

Good, but I see the spelling is still incorrect.

**Comment by tejas-2232** [comment]
> Updated as mentioned

Thank you! Its ready to merge but please also check spelling of the folder you've uploaded! 😃

**Comment by komalreddy3** [comment]
Updated . There is something wrong with my spelling vocabulary 😂

**Comment by tejas-2232** [comment]
> Updated . There is something wrong with my spelling vocabulary 😂

No problem 😄 
I know mistakes can happen. I also do sometimes.
Always check spellings before submissions.

**Pull request merged**
