### PR TITLE
Added code for Binary Search Trees in JS and renamed the folders for better structure of Repo

### PR DESCRIPTION
**Pull request by shreyanshchordia**
I have added code for Binary Trees in Javascript. Also renamed the Folders

### CODE REVIEW

**Comment by shreyanshchordia** [comment]
Please merge my PR for Hacktober Fest!!

**Comment by tejas-2232** [comment]
I have merged it.
       check the PR status on hacktoberfest site and give me feedback of
the PR status.
So that I can also tell my friends.

Regards,
Tejas

**Comment by shreyanshchordia** [comment]
Thank you! Yes my Pull request has been accepted! 😊

**Comment by tejas-2232** [comment]
Can you share the photo of it?
My other PR are still pending

**Comment by tejas-2232** [comment]
### Hey, you have not added the problem description in the README file
## Update it as soon as possible, otherwise I will have to revert the merge until you add it.

**Comment by shreyanshchordia** [comment]
Apologies for the same. This will be done by tomorrow.

**Comment by shreyanshchordia** [comment]
Hey I did the changes in README.md. Haven't heard from you? Are the changes
okay? Let me know.

**Pull request merged**
